
services:
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    
    volumes:
      # grafana data
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

    

    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
      - INFLUXDB_ORG=$INFLUXDB_ORG
      - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
      - INFLUXDB_BUCKET=$INFLUXDB_BUCKET

      
    depends_on:
      - influxdb


  influxdb:
    image: influxdb:2.8.0
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: admin
      DOCKER_INFLUXDB_INIT_BUCKET: proximity_sensor

    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2     

volumes:
  grafana-storage:
    driver: local 
  influxdb2-data:
  influxdb2-config:



secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./.env.influxdb2-admin-token